In [1]:
import pandas as pd

In [2]:
sales = pd.read_csv("sales.csv")
sales.head()

,Year,Product line,Product type,Product,Order method type,Retailer country,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
0,2004,Golf Equipment,Golf Accessories,Course Pro Golf and Tee Set,Sales visit,United States,5819.70,6586.16,1733.2,619.0,2.8,10.64,4086.50,5.105
1,2004,Golf Equipment,Golf Accessories,Course Pro Golf and Tee Set,Sales visit,United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2005,Golf Equipment,Golf Accessories,Course Pro Golf and Tee Set,Sales visit,United States,10904.28,11363.52,2990.4,1068.0,2.8,10.64,7913.88,10.210
3,2005,Golf Equipment,Golf Accessories,Course Pro Golf and Tee Set,Sales visit,United Kingdom,27987.84,28855.68,7593.6,2712.0,2.8,10.64,20394.24,10.320
4,2006,Golf Equipment,Golf Accessories,Course Pro Golf and Tee Set,Sales visit,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
sales.columns

Index([u'Year', u'Product line', u'Product type', u'Product',
       u'Order method type', u'Retailer country', u'Revenue',
       u'Planned revenue', u'Product cost', u'Quantity', u'Unit cost',
       u'Unit price', u'Gross profit', u'Unit sale price'],
      dtype='object')

In [4]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17823 entries, 0 to 17822
Data columns (total 14 columns):
Year                 17823 non-null int64
Product line         17823 non-null object
Product type         17823 non-null object
Product              17823 non-null object
Order method type    17823 non-null object
Retailer country     17823 non-null object
Revenue              6045 non-null float64
Planned revenue      6045 non-null float64
Product cost         6045 non-null float64
Quantity             5860 non-null float64
Unit cost            6045 non-null float64
Unit price           6045 non-null float64
Gross profit         6045 non-null float64
Unit sale price      6045 non-null float64
dtypes: float64(8), int64(1), object(5)
memory usage: 1.9+ MB

In [5]:
sales.describe()

,Year,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
count,17823.000000,6.045000e+03,6.045000e+03,6.045000e+03,5860.000000,6045.000000,6045.000000,6.045000e+03,6045.000000
mean,2005.164955,1.038455e+05,1.058923e+05,5.701932e+04,4691.273549,58.882618,48.900855,4.336203e+04,44.795072
std,0.956260,1.836042e+05,1.881274e+05,1.117846e+05,8950.955313,348.369401,62.814500,7.185831e+04,58.399255
min,2004.000000,0.000000e+00,0.000000e+00,3.360000e+01,5.000000,0.850000,3.660000,-1.336560e+04,0.000000
25%,2004.000000,1.364924e+04,1.383736e+04,5.759760e+03,625.000000,2.760000,7.000000,7.009650e+03,6.580000
50%,2005.000000,4.154119e+04,4.189571e+04,1.906720e+04,1695.000000,9.000000,18.000000,1.894653e+04,17.650000
75%,2006.000000,1.120026e+05,1.144758e+05,5.796000e+04,4858.000000,34.970000,66.770000,5.002308e+04,62.760000
max,2007.000000,3.644349e+06,3.477910e+06,2.061750e+06,164142.000000,7833.000000,265.140000,1.416160e+06,265.140000

In [6]:
sales.quantile([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

,Year,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
0.1,2004.0,4500.000,4677.456,1685.988,259.0,1.880000,6.00,2500.320,5.490000
0.2,2004.0,10184.888,10384.020,3993.504,495.0,2.420000,6.59,5342.104,6.000000
0.3,2004.0,17967.612,18210.880,7540.816,781.0,2.800000,8.00,8732.020,7.000000
0.4,2005.0,28502.354,28774.800,12444.132,1151.0,5.600000,12.81,13380.776,11.304500
0.5,2005.0,41541.190,41895.710,19067.200,1695.0,9.000000,18.00,18946.530,17.650000
0.6,2005.0,59452.444,61323.904,29127.864,2571.8,15.930000,35.00,27107.838,24.390000
0.7,2006.0,90163.784,91491.844,44843.860,3891.0,32.951029,54.93,40633.834,49.414263
0.8,2006.0,145288.136,146890.684,75031.920,6311.2,60.000000,90.09,62452.036,83.780000
0.9,2006.0,262308.196,265536.964,145997.700,11524.7,79.560000,129.72,107435.346,123.230000
1.0,2007.0,3644349.300,3477909.780,2061750.000,164142.0,7833.000000,265.14,1416159.780,265.140000

In [7]:
sales['Year'].unique()

array([2004, 2005, 2006, 2007])

In [8]:
sales['Product line'].unique()

array(['Golf Equipment', 'Camping Equipment', 'Outdoor Protection',
       'Mountaineering Equipment'], dtype=object)

In [9]:
sales['Product type'].unique()

array(['Golf Accessories', 'Sleeping Bags', 'Cooking Gear', 'First Aid',
       'Insect Repellents', 'Climbing Accessories'], dtype=object)

In [10]:
sales['Product'].unique()

array(['Course Pro Golf and Tee Set', 'Hibernator Self - Inflating Mat',
       'TrailChef Deluxe Cook Set', 'Deluxe Family Relief Kit',
       'Course Pro Golf Bag', 'TrailChef Water Bag',
       'TrailChef Kitchen Kit', 'TrailChef Cook Set',
       'TrailChef Single Flame', 'TrailChef Double Flame',
       'Hibernator Camp Cot', 'BugShield Lotion Lite',
       'Compact Relief Kit', 'Insect Bite Relief', 'Course Pro Umbrella',
       'Course Pro Gloves', 'Firefly Climbing Lamp',
       'Firefly Rechargeable Battery', 'Granite Chalk Bag',
       'TrailChef Canteen', 'TrailChef Cup', 'TrailChef Kettle',
       'TrailChef Utensils', 'Hibernator Lite', 'Hibernator Extreme',
       'Hibernator Pad', 'Hibernator Pillow', 'BugShield Natural',
       'BugShield Spray', 'BugShield Lotion', 'BugShield Extreme',
       'Calamine Relief', 'Aloe Relief', 'Granite Carabiner',
       'Granite Belay', 'Granite Pulley', 'Firefly Charger', 'Hibernator'],
      dtype=object)

In [11]:
sales['Order method type'].unique()

array(['Sales visit', 'Telephone', 'Web', 'Special', 'Mail', 'E-mail',
       'Fax'], dtype=object)

In [12]:
sales['Retailer country'].unique()

array(['United States', 'United Kingdom', 'Canada', 'Mexico', 'Brazil',
       'Japan', 'Korea', 'China', 'Singapore', 'Australia', 'Netherlands',
       'Sweden', 'Finland', 'Denmark', 'France', 'Germany', 'Belgium',
       'Switzerland', 'Austria', 'Italy', 'Spain'], dtype=object)

In [13]:
sales['Year'].value_counts()

2006    5451
2005    5451
2004    5451
2007    1470
Name: Year, dtype: int64

In [14]:
sales['Product line'].value_counts()

Camping Equipment           8562
Outdoor Protection          4410
Mountaineering Equipment    3087
Golf Equipment              1764
Name: Product line, dtype: int64

In [15]:
sales['Product type'].value_counts()

Cooking Gear            5880
Climbing Accessories    3087
Sleeping Bags           2682
Insect Repellents       2205
First Aid               2205
Golf Accessories        1764
Name: Product type, dtype: int64

In [16]:
sales['Order method type'].value_counts()

Special        2547
Fax            2547
E-mail         2547
Web            2547
Mail           2547
Telephone      2547
Sales visit    2541
Name: Order method type, dtype: int64

In [17]:
sales['Retailer country'].value_counts()

United Kingdom    865
United States     865
Switzerland       847
Brazil            847
Korea             847
Finland           847
Australia         847
Denmark           847
Mexico            847
Spain             847
China             847
Belgium           847
Japan             847
Germany           847
Netherlands       847
France            847
Italy             847
Singapore         847
Sweden            847
Austria           847
Canada            847
Name: Retailer country, dtype: int64

In [18]:
sales.groupby('Retailer country')['Revenue','Planned revenue','Product cost','Quantity','Gross profit'].sum()

,Revenue,Planned revenue,Product cost,Quantity,Gross profit
Retailer country,,,,,
Australia,1.526422e+07,1.552855e+07,8367046.10,649467.0,6384806.59
Austria,1.631419e+07,1.663918e+07,8923176.61,719084.0,6871597.34
Belgium,1.415299e+07,1.434713e+07,7695759.79,622150.0,5964513.37
Brazil,1.686686e+07,1.718625e+07,9210809.34,744353.0,7092849.29
Canada,3.918371e+07,3.975547e+07,21435997.54,1701123.0,16670505.63
China,4.350234e+07,4.432347e+07,23925152.71,1935454.0,18003637.37
Denmark,8.455457e+06,8.657223e+06,4695594.80,368479.0,3496915.24
Finland,2.714528e+07,2.768705e+07,14879340.33,1207265.0,11335187.27
France,3.595367e+07,3.640336e+07,19646425.37,1620252.0,14968952.89
Germany,3.509449e+07,3.565769e+07,19213400.37,1576459.0,14637047.69
Italy,2.601864e+07,2.649849e+07,14223866.13,1142868.0,10910074.30
Japan,4.603330e+07,4.691096e+07,25256321.68,2047615.0,19208447.45
Korea,3.174933e+07,3.226426e+07,17388109.35,1432122.0,13189782.95
Mexico,2.660842e+07,2.720830e+07,14559723.33,1173878.0,11175487.89
Netherlands,2.506122e+07,2.554392e+07,13716572.61,1121981.0,10464386.40
Singapore,2.886032e+07,2.945750e+07,15901641.50,1270886.0,11959852.99
Spain,2.367628e+07,2.415171e+07,12929558.31,1052358.0,9962395.94
Sweden,9.718640e+06,9.804136e+06,5258635.87,432962.0,4079646.04
Switzerland,1.065317e+07,1.079256e+07,5785329.90,465683.0,4489793.93
United Kingdom,3.988824e+07,4.081019e+07,22100106.53,1656837.0,16542988.78
United States,1.075452e+08,1.104916e+08,59569196.14,4549587.0,44714622.05

In [19]:
sales.groupby('Retailer country')['Revenue','Planned revenue','Product cost','Quantity','Unit cost','Unit price','Gross profit','Unit sale price'].mean()

,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
Retailer country,,,,,,,,
Australia,65794.049353,66933.410603,36064.853879,2873.747788,46.569968,46.828448,27520.718060,43.073775
Austria,63727.294570,64996.808203,34856.158633,2887.887550,53.321432,50.122734,26842.177109,45.285907
Belgium,58970.775000,59779.727417,32065.665792,2681.681034,48.276413,48.253708,24852.139042,44.445764
Brazil,106752.290633,108773.738987,58296.261646,4865.052288,79.542414,46.980759,44891.451203,43.213174
Canada,97959.284950,99388.685350,53589.993850,4395.666667,69.936654,47.781300,41676.264075,44.512998
China,192488.245442,196121.556814,105863.507566,8878.229358,110.158067,53.785133,79662.112257,49.097133
Denmark,41448.317206,42437.366471,23017.621569,1870.451777,41.523586,51.148088,17141.741373,46.517176
Finland,130506.174038,133110.827644,71535.290048,5976.559406,83.147766,47.003173,54496.092644,43.090212
France,89436.994279,90555.617189,48871.704900,4154.492308,59.163594,47.227438,37236.201219,43.252405
Germany,88399.215718,89817.861788,48396.474484,4084.090674,62.195636,50.447154,36869.137758,46.217439
Italy,85307.013082,86880.299279,46635.626656,3874.128814,60.447363,48.496754,35770.735410,44.434877
Japan,118034.096308,120284.509077,64759.799179,5416.970899,83.429044,47.312692,49252.429359,42.988547
Korea,123538.232763,125541.879144,67658.013035,5705.665339,68.223581,48.365798,51322.112646,44.200622
Mexico,96407.300906,98580.800616,52752.620761,4380.141791,54.945672,46.842319,40490.898152,42.961267
Netherlands,79559.427175,81091.815937,43544.674952,3678.626230,58.807858,49.378000,33220.274286,44.626565
Singapore,99176.345945,101228.521924,54644.816151,4522.725979,69.325948,49.999931,41099.151168,45.866685
Spain,79718.122424,81318.879529,43533.866364,3654.020833,61.862859,46.400303,33543.420673,42.942191
Sweden,40494.333792,40850.566583,21910.982792,1858.206009,47.705907,53.585125,16998.525167,49.215721
Switzerland,58533.873736,59299.777143,31787.526923,2616.196629,42.835353,46.807912,24669.197418,42.730779
United Kingdom,140947.836996,144205.602968,78092.249223,6046.850365,25.784710,49.579470,58455.790742,45.249123
United States,221286.423807,227349.010638,122570.362428,9700.611940,26.623756,50.446646,92005.395165,46.354537

In [20]:
sales.dropna().groupby('Retailer country')['Revenue','Planned revenue','Product cost','Quantity','Unit cost','Unit price','Gross profit','Unit sale price'].min()

,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
Retailer country,,,,,,,,
Australia,0.0,294.00,120.78,49.0,0.85,3.66,-558.00,0.000000
Austria,0.0,0.00,33.60,5.0,0.85,3.66,-360.00,0.000000
Belgium,0.0,0.00,70.18,6.0,0.85,3.66,-280.72,0.000000
Brazil,966.0,966.00,455.63,138.0,0.85,3.66,510.37,3.192857
Canada,198.0,198.00,93.39,33.0,0.85,3.66,53.40,2.875000
China,0.0,618.00,291.49,103.0,0.85,3.66,-840.00,0.000000
Denmark,0.0,738.00,312.96,40.0,0.85,3.66,-2561.74,0.000000
Finland,486.0,486.00,223.56,81.0,0.85,3.66,262.44,3.141429
France,0.0,230.12,90.24,43.0,0.85,3.66,-190.40,0.000000
Germany,234.0,0.00,110.37,32.0,0.85,3.66,-1119.04,0.000000
Italy,0.0,330.00,154.56,55.0,0.85,3.66,-224.00,0.000000
Japan,0.0,0.00,67.20,22.0,0.85,3.66,-1225.18,0.000000
Korea,276.0,276.00,130.18,46.0,0.85,3.66,-3831.84,3.137143
Mexico,432.0,432.00,203.76,51.0,0.85,3.66,-542.00,2.615000
Netherlands,0.0,308.57,113.28,40.0,0.85,3.66,-13365.60,0.000000
Singapore,576.0,576.00,271.68,32.0,0.85,3.66,1.28,3.142857
Spain,348.0,348.00,160.08,40.0,0.85,3.66,103.68,2.200000
Sweden,0.0,0.00,67.76,23.0,0.85,3.66,-1438.56,0.000000
Switzerland,0.0,162.00,74.52,27.0,0.85,3.66,-2790.00,0.000000
United Kingdom,0.0,264.00,124.52,44.0,0.85,3.66,-4009.68,0.000000
United States,0.0,156.90,57.60,24.0,0.85,3.66,-186.00,0.000000

In [21]:
sales.groupby('Year')['Revenue','Planned revenue','Product cost','Quantity','Unit cost','Unit price','Gross profit','Unit sale price'].sum()

,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
Year,,,,,,,,
2004,1.528977e+08,1.567331e+08,8.538058e+07,7318558.0,97750.174438,92781.46,62482134.57,84841.786496
2005,1.908502e+08,1.947044e+08,1.029861e+08,8453776.0,113381.098628,103147.42,81126260.32,93071.003707
2006,2.228721e+08,2.270020e+08,1.209524e+08,8786835.0,134772.241249,82126.84,95563977.64,76786.074337
2007,6.112591e+07,6.167953e+07,3.536268e+07,2931694.0,10041.912620,17549.95,22951118.87,16087.343791

In [22]:
sales.groupby('Product line')['Revenue','Planned revenue','Product cost','Quantity','Unit cost','Unit price','Gross profit','Unit sale price'].sum()

,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
Product line,,,,,,,,
Camping Equipment,4.860065e+08,4.966410e+08,2.862390e+08,15200145.0,323199.354903,214876.61,1.825174e+08,195361.436414
Golf Equipment,4.205702e+07,4.235803e+07,1.525444e+07,2367637.0,14195.740000,39488.03,2.483757e+07,36115.529168
Mountaineering Equipment,5.254793e+07,5.293751e+07,2.522232e+07,3672582.0,11540.322032,24108.88,2.639106e+07,23103.209617
Outdoor Protection,4.713449e+07,4.818252e+07,1.796598e+07,6250499.0,7010.010000,17132.15,2.837751e+07,16206.033132

In [23]:
sales.groupby('Product type')['Revenue','Planned revenue','Product cost','Quantity','Unit cost','Unit price','Gross profit','Unit sale price'].sum()

,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
Product type,,,,,,,,
Climbing Accessories,5.254793e+07,5.293751e+07,2.522232e+07,3672582.0,11540.322032,24108.88,2.639106e+07,23103.209617
Cooking Gear,2.859992e+08,2.888950e+08,1.671281e+08,13390271.0,57293.698207,100202.17,1.057078e+08,89698.697296
First Aid,1.175132e+07,1.230833e+07,6.032276e+06,770426.0,5358.250000,11885.57,5.550439e+06,11231.226854
Golf Accessories,4.205702e+07,4.235803e+07,1.525444e+07,2367637.0,14195.740000,39488.03,2.483757e+07,36115.529168
Insect Repellents,3.538318e+07,3.587419e+07,1.193371e+07,5480073.0,1651.760000,5246.58,2.282707e+07,4974.806279
Sleeping Bags,2.000073e+08,2.077460e+08,1.191109e+08,1809874.0,265905.656696,114674.44,7.680951e+07,105662.739118

In [24]:
sales.groupby('Product')['Revenue','Planned revenue','Product cost','Quantity','Unit cost','Unit price','Gross profit','Unit sale price'].mean()

,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
Product,,,,,,,,
Aloe Relief,4629.345409,4807.880881,1806.925283,941.106918,1.920000,5.230000,2708.311824,4.923531
BugShield Extreme,96957.617200,98752.567200,34861.081829,14405.405714,2.420000,7.000000,60011.262571,6.297800
BugShield Lotion,30466.100427,30854.084390,10374.154512,4452.426829,2.330000,7.000000,19779.042500,6.843890
BugShield Lotion Lite,18290.528015,18216.961103,4947.441176,2631.617647,1.880000,7.000000,13138.724412,6.924242
BugShield Natural,41946.486667,42286.609259,13326.716296,7164.901235,1.860000,6.000000,27916.972222,5.821106
BugShield Spray,26179.175506,26610.653101,8227.066139,4495.664557,1.830000,6.010000,17543.818481,5.478337
Calamine Relief,3843.042105,3842.278947,1812.987368,640.631579,2.830000,6.000000,2028.544211,5.997566
Compact Relief Kit,23210.543905,22761.464142,9302.031361,1026.988166,9.035503,23.000000,13049.248876,22.190085
Course Pro Gloves,57082.367945,50092.319247,14443.691575,5703.006849,2.551644,10.710000,31651.792260,9.779597
Course Pro Golf Bag,110022.940769,117373.296154,42656.870513,545.210526,79.700000,219.300000,67366.070256,204.491247
Course Pro Golf and Tee Set,43725.838625,46166.893500,12149.182500,4338.993750,2.800000,10.640000,31576.656125,7.954244
Course Pro Umbrella,60912.608089,59538.914331,28963.834395,4827.305732,6.000000,12.810000,29649.901592,9.645824
Deluxe Family Relief Kit,37055.997619,41179.761905,23174.953741,1197.180556,17.577415,35.000000,13881.043878,31.828917
Firefly Charger,96909.559143,97835.504476,41549.990857,1858.228571,22.360000,52.990000,54727.540762,51.767433
Firefly Climbing Lamp,49575.633178,47845.668505,27333.713458,1270.700935,21.712542,39.990000,19272.257850,37.559888
Firefly Rechargeable Battery,65154.034175,64198.824854,25989.854854,8250.747573,3.150000,8.000000,37357.023592,7.330598
Granite Belay,108865.070588,111625.596078,55801.185000,1618.833333,34.470000,70.000000,51371.148333,66.101961
Granite Carabiner,74181.161584,75983.864950,37732.192871,19251.118812,1.960000,4.000000,35428.358416,3.804509
Granite Chalk Bag,21682.954528,21638.003774,10308.826887,1208.537736,8.530000,18.000000,11258.452170,17.813382
Granite Pulley,90114.651238,91228.673714,44404.728095,2419.876190,18.350000,38.000000,44983.301619,36.940911
Hibernator,767540.070714,821723.607143,481292.857143,5596.428571,86.000000,146.830000,286247.213571,137.289046
Hibernator Camp Cot,149116.872045,145402.841534,95117.520170,1460.000000,63.938288,104.480000,46861.393409,90.237163
Hibernator Extreme,365562.397086,373475.957257,215221.714286,1434.811429,150.000000,265.140000,143390.737886,249.636058
Hibernator Lite,240837.047611,246733.765833,167279.000000,2787.983333,60.000000,90.090000,69122.394944,84.602833
Hibernator Pad,88104.396203,95799.246519,44112.366076,2461.069620,18.626564,40.650000,39748.796582,36.738118
Hibernator Pillow,35674.584702,37091.291589,17851.583245,2156.099338,8.429277,17.650000,16859.139735,16.606556
Hibernator Self - Inflating Mat,205569.080904,226799.454237,102783.789548,1443.000000,1198.772316,127.270000,102785.291356,116.564514
Insect Bite Relief,5953.472892,5944.199277,2748.145301,995.704819,2.760000,6.000000,3175.297952,5.986907
TrailChef Canteen,55651.043048,58136.770667,31466.213238,4598.680952,6.847911,12.979524,22502.923190,11.908531
TrailChef Cook Set,200210.461514,193758.393073,129841.533073,3732.935780,34.530638,54.930000,59077.159128,45.817427
TrailChef Cup,29935.345202,32361.992576,7803.481364,9152.136364,0.852305,3.660000,20997.037323,3.381146
TrailChef Deluxe Cook Set,260760.561029,281146.480000,174155.910980,2182.101010,78.802887,129.720000,86604.650049,110.741704
TrailChef Double Flame,174853.879327,169279.121971,88542.908654,1180.572115,75.000000,151.770000,76414.662692,139.231316
TrailChef Kettle,139105.560415,152412.445078,58930.125181,12108.549223,5.110878,13.220000,72512.859585,11.749074
TrailChef Kitchen Kit,107371.240476,105129.013651,72002.322751,4585.550265,15.760641,23.800000,31361.835079,22.689863
TrailChef Single Flame,211024.540188,206942.394883,149481.433521,3222.971831,46.380000,66.770000,53287.672394,62.793426
TrailChef Utensils,78118.765619,82572.624048,41006.969048,4390.904762,9.727192,19.290000,34983.867762,18.156017
TrailChef Water Bag,123522.910556,114682.265278,52277.802685,19948.277778,2.762045,6.590000,54468.222593,5.764350

In [25]:
sales.groupby('Order method type')['Revenue','Planned revenue','Product cost','Quantity','Gross profit'].sum()

,Revenue,Planned revenue,Product cost,Quantity,Gross profit
Order method type,,,,,
E-mail,3.238293e+07,3.301196e+07,1.768881e+07,1503654.0,1.352462e+07
Fax,1.376507e+07,1.399805e+07,7.399451e+06,653190.0,5.993243e+06
Mail,9.749679e+06,9.942812e+06,5.211545e+06,483151.0,4.175907e+06
Sales visit,6.946909e+07,7.141927e+07,3.870416e+07,3084491.0,2.890578e+07
Special,6.642340e+06,6.618693e+06,3.550795e+06,324760.0,2.824776e+06
Telephone,7.056328e+07,7.230265e+07,3.889483e+07,3200421.0,2.907046e+07
Web,4.251736e+08,4.328256e+08,2.332322e+08,18241196.0,1.776287e+08